### ISSUE TITLE
Optionally install systemd units into runtime directory

### ISSUE THREAD

**Issue by znerol** [znerol/ansible-collection-podluck#12]
One of the more interesting use-cases this ansible collection covers is the ability to setup one deployment script for local, staging and production deployments by using different inventories for each environment.

For local deployments (i.e., rootless pods), the systemd units are copied to `.config/systemd/user`. However, those units persist across logins/reboots. Hence, the pods are started automatically on subsequent login sessions.

This nuisance could be resolved if units could optionally be copied to one of the numerous non-persisting directories in the [search path](https://www.freedesktop.org/software/systemd/man/systemd.unit.html#).

**Comment by znerol** [comment]
This can be achieved to some degree using the existing mechanisms. Just specify the following vars in the local inventory:

```yaml
        podluck_systemd_scope: user
        podluck_systemd_unit_dir: >-
          {{ lookup('env', 'XDG_RUNTIME_DIR') }}/systemd/user
        podluck_systemd_config_dir: >-
          {{ lookup('env', 'XDG_RUNTIME_DIR') }}/systemd/user
```

Regrettably, `systemctl enable` will still put symlinks into `.confi/systemd/user`. In order to instruct `systemctl enable` to use the runtime directory, the `--runtime` flag needs to be used. However, it looks like the systemd ansible task currently [doesn't support](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/systemd_module.html) that flag.
